---
registry_user: 
registry_pass: 
registry_email:
mirror_required: false
dns_required: true
dhcp_required: true
haproxy_required: true
time_required: true
bare_net_name: baremetal
provisioner:                 
  name: bastion              
  interface1: eno1 #private          
  ipaddr1: "192.168.11.2" 
  prefix1: "24"
  interface2: eno2 #lmi           
  ipaddr2: "192.168.85.2"
  prefix2: "24"
  gateway2: "192.168.85.1"
dns:
  domain: "randalllabs.com"
  cluster_name: "test"
  forwarder1: 192.168.80.2
  forwarder2: 192.168.80.4
dhcp:
  router: "192.168.11.1"
  bcast: "192.168.11.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.11.100"
  poolend: "192.168.11.200"
  ipid: "192.168.11.0"
  netmaskid: "255.255.255.0"
bootstrap:
  - name: "bootstrap"
    ipaddr: '10.10.10.10'
    gateway: '10.10.10.1'
masters:
  - name: "control0"
    ipaddr: "192.168.11.101"
    macaddr: "14:02:EC:ED:C3:E8"
    ilo_ip: "192.168.10.13"
    ilo_user: 
    ilo_pw: 
    root_device: /dev/sda
  - name: "control1"
    ipaddr: "192.168.11.102"
    macaddr: "94:57:A5:A8:C0:C8"
    ilo_ip: "192.168.10.14"
    ilo_user: 
    ilo_pw: 
    root_device: /dev/sda
  - name: "control2"
    ipaddr: "192.168.11.103"
    macaddr: "34:64:A9:B9:9D:90"
    ilo_ip: "192.168.10.15"
    ilo_user: 
    ilo_pw: 
    root_device: /dev/sda
api_ip: "192.168.11.3"
apps_ip: "192.168.11.4"
networkifacename: baremetal
oc_cli_tar: oc-4.11.13-linux.tar.gz
oc_mirror_tar: oc-mirror.tar.gz
haproxy_control: false
time_server:
  - name: 192.168.85.1
  - name: 192.168.80.1
registry_server: "registry.{{ dns.cluster | lower }}.{{ dns.domain | lower }}"
mirror_metadata_storage: /var/opt/mirror
mirror_tarball: mirror_content.tar
mirror_tarball_dest: /tmp
registry_port: 5050
local_mirror_path: '/tmp/mirror/'
ipi_installer: "openshift-baremetal-install"
podman_http_port: 8080
rhcos_image: rhcos-411.86.202210041459-0-qemu.x86_64.qcow2.gz
rhcos_image_sha256: 5dbc9dc6bb358a335ce353dd0c0f84bf3960ba855bc501d40edd3d44c26e19a1
cert_chain: true
disconnected: true
prov_user: kni