---
network_connections:
  - name: "{{ provisioner.interface2 }}"
    state: up
    type: ethernet
    interface_name: "{{ provisioner.interface2 }}"
    ip:
      address:
        - "{{ provisioner.ipaddr2 }}/{{ provisioner.prefix2 }}"
      gateway4: "{{ provisioner.gateway2 }}"
      dns:
        - 127.0.0.1
        - "{{ dns.forwarder1 }}"
        - "{{ dns.forwarder2 }}"
      dns_search: "{{ dns.domain }}"

  - name: "{{ bare_net_name }}"
    type: bridge
    state: up
    interface_name: "{{ bare_net_name }}"
    ip:
      address:
        - "{{ provisioner.ipaddr1 }}/{{ provisioner.prefix1 }}"

  - name: "{{ provisioner.interface1 }}"
    state: up
    type: ethernet
    interface_name: "{{ provisioner.interface1 }}"
    controller: "{{ bare_net_name }}"
    port_type: bridge
