---
- name: Extract the OC CLI utility
  ansible.builtin.unarchive:
    src: "{{ oc_cli_tar }}"
    dest: /usr/local/bin/
    include:
      - oc
  become: true

- name: Extract the OC Mirror utility
  ansible.builtin.unarchive:
    src: "{{ oc_mirror_tar }}"
    dest: /usr/local/bin/
  become: true

- name: ensure required variables are set
  ansible.builtin.assert:
    that:
      - registry_user is defined
      - registry_pass is defined
      - registry_email is defined

- name: create registry credentials
  ansible.builtin.shell:
    cmd: "echo -n '{{ registry_user }}:{{ registry_pass }}' | base64 -w0"
  register: credentials

- name: Set fact for credentials
  ansible.builtin.set_fact:
    registry_creds: "{{ credentials.stdout }}"

- name: "Create {{ mirror_metadata_storage }} directory"
  ansible.builtin.file: 
    dest: "{{ mirror_metadata_storage }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  become: true

- name: create directory for config.json.j2
  ansible.builtin.file:
    path: ~/.docker
    state: directory
    
- name: create pull secret for local registry
  ansible.builtin.template:
    src: config.json.j2
    dest: ~/.docker/config.json

- name: Copy tarball onto host
  ansible.builtin.copy:
    src: "{{ mirror_tarball }}"
    dest: "{{ mirror_tarball_dest }}"

- name: run the mirror sync command
  ansible.builtin.shell:
    cmd: "oc mirror --from={{ mirror_tarball_dest }}/{{ mirror_tarball }}  docker://{{ registry_server }}:{{ registry_port }} "
    chdir: "/home/{{ ansible_user_id }}"

- name: find directory that contains mirror yaml files
  ansible.builtin.find:
    paths: "/home/{{ ansible_user_id }}/oc-mirror-workspace/"
    file_type: directory
    patterns: results*
  register: mirror_dir
  
- name: find YAML files in above directory
  ansible.builtin.find:
    paths: "{{ mirror_dir.files.0.path }}"
    patterns: '*.yml,*.yaml'
  register: yaml_files

- name: Make directory to store mirror config files
  ansible.builtin.file:
    path: "{{ local_mirror_path }}"
    state: directory
  delegate_to: localhost

- name: fetch yaml files
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "{{ local_mirror_path }}"
    flat: true
  loop: "{{ yaml_files.files }}"
