---
- name: Install RHEL System Roles
  hosts: localhost
  become: true
  tasks:
    - name: Install RHEL Ansible Roles
      ansible.builtin.yum:
        name: rhel-system-roles
        state: present
