---
- name: Setup Provisioner for OCP Bare Metal IPI
  hosts: provisioner
  become: true
  tasks:
    - ansible.builtin.include_tasks: 1_install_rhel_roles.yaml

    - ansible.builtin.include_role:
        name: rhel-system-roles.network

    - ansible.builtin.include_role:
        name: dns
      when: dns_required

    - ansible.builtin.include_role:
        name: dhcp
      when: dhcp_required

    - ansible.builtin.include_role:
        name: haproxy
      when: haproxy_required

    - ansible.builtin.include_role:
        name: time
      when: time_required

    - ansible.builtin.include_role:
        name: ocp-mirror
      when: mirror_required

    - ansible.builtin.include_tasks: 8_sync_registry.yaml

    - ansible.builtin.include_role:
        name: pre-ocp

    - ansible.builtin.include_role:
        name: deploy_ocp