---
- name: Install packages for DHCP/PXE install
  ansible.builtin.yum:
    name: "{{ dhcppkgs }}"
    state: present

- name: Write out dhcp file 
  ansible.builtin.template:
    src: ../templates/dhcpd-uefi.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify:
    - restart dhcpd

- name: Open Firewall for dhcp
  ansible.posix.firewalld: 
    service: dhcp
    state: enabled
    permanent: true
    immediate: true