---
prov_user: kni
password: "{{ lookup('password', 'credentials/' + prov_user + ' length=15 chars=ascii_letters,digits,punctuation') }}"
prov_packages:
  - libvirt
  - qemu-kvm
  - mkisofs
  - python3-devel
  - jq
  - ipmitool
libvirt_default_pool: "/var/lib/libvirt/images"
image_pool_name: "default"
prov_firewall_svc: 
  - http
libvirt_uri: "qemu:///system"
